- hosts: localhost

  vars_files:
    - default.config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      homebrew_taps:
        - homebrew/core
        - homebrew/bundle
      homebrew_brewfile_dir: .
      tags: ['homebrew']

  tasks:
    - import_tasks: tasks/ssh.yml
      tags: ['ssh']
