---
- name: Checkout latest base16-shell config repository
  ansible.builtin.git:
    repo: 'https://github.com/chriskempson/base16-shell.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/base16-shell"

- name: Checkout latest tinted-shell config repository
  ansible.builtin.git:
    repo: 'https://github.com/tinted-theming/tinted-shell'
    dest: "{{ lookup('env', 'HOME') }}/.config/tinted-shell"

- name: Checkout latest base16-kitty config repository
  ansible.builtin.git:
    repo: 'https://github.com/kdrag0n/base16-kitty.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/base16-kitty"
