---
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:phantomwhale/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    accept_hostkey: yes
    version: master

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install-osx.sh
