---
- name: Cloning .dotfiles
  git:
    repo: 'https://github.com/phantomwhale/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    accept_hostkey: yes
    version: master

- name: Fix git remote
  git_config:
    repo: "{{ lookup('env', 'HOME') }}/.dotfiles"
    scope: 'local' 
    name: 'remote.origin.url'
    value: 'git@github.com:phantomwhale/dotfiles.git'

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install-osx.sh
