---
- name: Install node support for neovim
  shell: "eval $({{ homebrew_brew_bin_path }}/fnm env) && npm install -g neovim"

- name: Install python support for neovim
  shell: "pip3 install --user --upgrade pynvim"

- name: Install node tooling used by neovim LSP plugins
  shell: "eval $({{ homebrew_brew_bin_path }}/fnm env) && npm install -g typescript typescript-language-server diagnostic-languageserver eslint prettier"
