---
- name: "Disable periods after two spaces"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: int
    value: 0

- name: "Stop Mission Control rearranging spaces"
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false

- name: "Do not reveal wallpaper when clicking on desktop"
  osx_defaults:
    domain: com.apple.WindowManager
    key: EnableStandardClickToShowDesktop
    type: int
    value: 0
