---
- name: Install rubies
  shell: 'ruby-install --latest --no-reinstall {{ item }} -- --with-openssl-dir="$(brew --prefix openssl@1.1)"'
  with_items: "{{ ruby_versions }}"

- name: Install ruby gem tools
  shell: 'chruby-exec "$1" -- source /usr/local/share/chruby/chruby.sh; gem install --no-document timetrap neovim solargraph rufo rubocop rubocop-rails rubocop-rails'
  with_items: "{{ ruby_versions }}"
